### ISSUE TITLE
Why the preference for Dolphin Phi over regular Phi, Mistral or Llama2?

### ISSUE THREAD

**Issue by DamianB-BitFlipper** [collabora/WhisperFusion#22]
Just curious to understand your decision process on this.

**Comment by zoq** [comment]
Dolphin Phi over regular Phi; you can use any tuned phi model, you can just update:

https://github.com/collabora/WhisperFusion/blob/main/docker/scripts/build-dolphin-2_6-phi-2.sh#L10

with whatever you want to use, but make sure to update the model format as well. On paper Dolphin Phi outperforms regular Phi on certain tasks, that was the main reason why we added it in the first place. That said, we couldn't really see a huge difference between the two, but since both models worked we left dolphin as the default. We tested Mistral and LLama as well, but both models are bigger, which comes with extra latency.

We are currently evaluating if we can finetune phi on specific tasks and have a mixture of tuned phi models, which would give us a good balance of both worlds.

**Comment by DamianB-BitFlipper** [comment]
What do you mean by “update the model format as well?”On Feb 1, 2024, at 00:19, Marcus Edel ***@***.***> wrote:﻿
Dolphin Phi over regular Phi; you can use any tuned phi model, you can just update:
https://github.com/collabora/WhisperFusion/blob/main/docker/scripts/build-dolphin-2_6-phi-2.sh#L10
with whatever you want to use, but make sure to update the model format as well. On paper Dolphin Phi outperforms regular Phi on certain tasks, that was the main reason why we added it in the first place. That said, we couldn't really see a huge difference between the two, but since both models worked we left dolphin as the default. We tested Mistral and LLama as well, but both models are bigger, which comes with extra latency.
We are currently evaluating if we can finetune phi on specific tasks and have a mixture of tuned phi models, which would give us a good balance of both worlds.

**Comment by zoq** [comment]
Different models use different prompt formats:

https://github.com/collabora/WhisperFusion/blob/main/llm_service.py#L170-L188

implements:

https://huggingface.co/TheBloke/dolphin-2_6-phi-2-GGUF#prompt-template-chatml

**Comment by DamianB-BitFlipper** [comment]
Oh I understand now. Thanks for the clarification. DamianOn Feb 1, 2024, at 00:53, Marcus Edel ***@***.***> wrote:﻿
Different models use different prompt formats:
https://github.com/collabora/WhisperFusion/blob/main/llm_service.py#L170-L188
implements:
https://huggingface.co/TheBloke/dolphin-2_6-phi-2-GGUF#prompt-template-chatml
